"""Tests for JSON -> Markdown rendering."""

from __future__ import annotations

import shutil
from pathlib import Path

from papercheck.core import segments as segments_mod
from papercheck.core import texscan
from papercheck.core.gate import run_gate
from papercheck.core.paths import audit_dir
from papercheck.core.render import render_all

FIXTURE = Path(__file__).parent / "fixtures" / "toy_clean_paper"


def _prepare(tmp_path: Path) -> Path:
    dst = tmp_path / "paper"
    shutil.copytree(FIXTURE, dst)
    audit = dst / "Paper_Audit"
    if audit.exists():
        shutil.rmtree(audit)
    return dst


def test_render_writes_segment_map_and_gate(tmp_path) -> None:
    root = _prepare(tmp_path)
    structure = texscan.scan(root)
    segments_mod.write_segments(root, structure)
    result = run_gate(root, mechanical_only=True)

    render_all(root)

    out = audit_dir(root)
    seg_md = out / "03_segment_map.md"
    gate_md = out / "10_final_acceptance_gate.md"
    assert seg_md.exists()
    assert gate_md.exists()

    seg_text = seg_md.read_text(encoding="utf-8")
    assert seg_text.startswith("# Segment Map\n\n_Generated by papercheck render._\n")
    assert "| S0 |" in seg_text

    gate_text = gate_md.read_text(encoding="utf-8")
    assert result["verdict"] in gate_text


def test_render_skips_absent_sources(tmp_path) -> None:
    root = tmp_path / "empty"
    root.mkdir()
    # No JSON artifacts at all -> render_all must not raise, writes nothing.
    render_all(root)
    out = audit_dir(root)
    assert not (out / "03_segment_map.md").exists()
    assert not (out / "10_final_acceptance_gate.md").exists()


def test_render_manual_queue(tmp_path) -> None:
    from papercheck.core import ledger

    root = tmp_path / "paper"
    root.mkdir()
    ledger.save_manual_check(
        root,
        {
            "check_id": "MANUAL-1",
            "question": "Verify the novelty claim.",
            "blocking": True,
            "resolved": False,
        },
    )
    render_all(root)
    queue = audit_dir(root) / "manual_check_queue.md"
    assert queue.exists()
    assert "MANUAL-1" in queue.read_text(encoding="utf-8")
