"""Rendering of audit artifacts into human-readable Markdown reports.

Markdown views are generated directly from the JSON artifacts produced by the
scanner, segmenter, ledger, and gate. No template files are required. Each
report is deterministic (stable ordering by id) and lands under the paper's
``Paper_Audit`` directory. Sources that are absent are skipped silently.
"""

from __future__ import annotations

import json
from pathlib import Path

from papercheck.core import ledger, paths

_HEADER_NOTE = "_Generated by papercheck render._"

_MANUAL_STATUS = "NEEDS_MANUAL_CHECK"


def _load_json(path: Path):
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def _preamble(title: str) -> list[str]:
    return [f"# {title}", "", _HEADER_NOTE, ""]


def _truncate(text: str, limit: int = 200) -> str:
    text = (text or "").replace("\n", " ").strip()
    if len(text) > limit:
        return text[: limit - 1].rstrip() + "…"
    return text


def _write(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _location_str(loc: dict) -> str:
    file = loc.get("file", "?")
    start = loc.get("line_start")
    if start is not None:
        return f"{file}:{start}"
    return file


def _render_segment_map(paper_root: Path, out_dir: Path) -> Path | None:
    segments = _load_json(paths.segments_file(paper_root))
    if segments is None:
        return None
    lines = _preamble("Segment Map")
    lines += [
        "| segment_id | title | budget | risk_score | reason |",
        "| --- | --- | --- | --- | --- |",
    ]
    for seg in sorted(segments, key=lambda s: s.get("segment_id", "")):
        lines.append(
            f"| {seg.get('segment_id', '')} "
            f"| {seg.get('title', '')} "
            f"| {seg.get('budget', '')} "
            f"| {seg.get('risk_score', '')} "
            f"| {seg.get('reason', '')} |"
        )
    out = out_dir / "03_segment_map.md"
    _write(out, lines)
    return out


def _render_proposed_ledger(paper_root: Path, out_dir: Path) -> Path | None:
    proposed = ledger.list_issues(paper_root, status="PROPOSED")
    if not proposed:
        return None
    lines = _preamble("Proposed Issue Ledger")
    for issue in sorted(proposed, key=lambda i: i.get("issue_id", "")):
        verification = issue.get("verification") or {}
        quote_found = verification.get("quote_found")
        status = (
            "verified"
            if quote_found is True
            else "unverified"
            if quote_found is None
            else "quote-not-found"
        )
        lines += [
            f"## {issue.get('issue_id', '')}",
            "",
            f"- **Severity:** {issue.get('severity_proposed', '')}",
            f"- **Category:** {issue.get('category', '')}",
            f"- **Location:** {_location_str(issue.get('location', {}))}",
            f"- **Exact quote:** {_truncate(issue.get('exact_quote', ''))}",
            f"- **Concrete failure mode:** {issue.get('concrete_failure_mode', '')}",
            f"- **Verification:** {status}",
            "",
        ]
    out = out_dir / "07_issue_ledger.proposed.md"
    _write(out, lines)
    return out


def _render_adjudicated_ledger(paper_root: Path, out_dir: Path) -> Path | None:
    all_issues = ledger.list_issues(paper_root)
    buckets = {
        "ACCEPTED": [],
        "REJECTED": [],
        _MANUAL_STATUS: [],
    }
    for issue in all_issues:
        status = issue.get("status")
        if status in ("ACCEPTED", "PATCH_PLANNED", "PATCHED", "REGRESSION_PASSED", "CLOSED"):
            buckets["ACCEPTED"].append(issue)
        elif status in ("REJECTED", "REJECTED_SOURCE_TARGET_INVALID"):
            buckets["REJECTED"].append(issue)
        elif status == _MANUAL_STATUS:
            buckets[_MANUAL_STATUS].append(issue)
    if not any(buckets.values()):
        return None
    lines = _preamble("Adjudicated Issue Ledger")
    titles = {
        "ACCEPTED": "Accepted",
        "REJECTED": "Rejected",
        _MANUAL_STATUS: "Needs Manual Check",
    }
    for key in ("ACCEPTED", "REJECTED", _MANUAL_STATUS):
        group = sorted(buckets[key], key=lambda i: i.get("issue_id", ""))
        if not group:
            continue
        lines += [f"## {titles[key]}", ""]
        for issue in group:
            adj = issue.get("adjudication") or {}
            severity = issue.get("severity_final") or issue.get("severity_proposed", "")
            lines += [
                f"### {issue.get('issue_id', '')}",
                "",
                f"- **Final severity:** {severity}",
                f"- **Decision:** {adj.get('decision') or '-'}",
                f"- **Rationale:** {adj.get('rationale') or '-'}",
                "",
            ]
    out = out_dir / "08_issue_ledger.adjudicated.md"
    _write(out, lines)
    return out


def _render_final_gate(paper_root: Path, out_dir: Path) -> Path | None:
    gate = _load_json(paths.audit_dir(paper_root) / "final_gate.json")
    if gate is None:
        return None
    lines = _preamble("Final Acceptance Gate")
    lines += [f"## Verdict: {gate.get('verdict', '')}", ""]

    blockers = gate.get("blockers", [])
    lines += ["### Blockers", ""]
    if blockers:
        for b in blockers:
            lines.append(f"- {b}")
    else:
        lines.append("- None")
    lines.append("")

    signals = gate.get("signals", {})
    lines += ["### Signals", "", "| signal | value |", "| --- | --- |"]
    for name in sorted(signals):
        value = signals[name]
        if isinstance(value, list):
            value = ", ".join(str(v) for v in value) if value else "-"
        lines.append(f"| {name} | {value} |")
    lines.append("")

    out = out_dir / "10_final_acceptance_gate.md"
    _write(out, lines)
    return out


def _render_manual_queue(paper_root: Path, out_dir: Path) -> Path | None:
    checks = ledger.list_manual_checks(paper_root)
    if not checks:
        return None
    lines = _preamble("Manual Check Queue")
    lines += [
        "| id | question | blocking | resolved | resolution |",
        "| --- | --- | --- | --- | --- |",
    ]
    for c in sorted(checks, key=lambda c: c.get("check_id", "")):
        lines.append(
            f"| {c.get('check_id', '')} "
            f"| {_truncate(c.get('question', ''))} "
            f"| {c.get('blocking', False)} "
            f"| {c.get('resolved', False)} "
            f"| {c.get('resolution') or '-'} |"
        )
    out = out_dir / "manual_check_queue.md"
    _write(out, lines)
    return out


def render_all(paper_root: Path) -> None:
    """Render all available Markdown reports for a paper's audit."""
    paper_root = Path(paper_root)
    out_dir = paths.audit_dir(paper_root)
    # reports_dir is reserved for future per-segment reports; ensure it exists.
    paths.reports_dir(paper_root).mkdir(parents=True, exist_ok=True)

    _render_segment_map(paper_root, out_dir)
    _render_proposed_ledger(paper_root, out_dir)
    _render_adjudicated_ledger(paper_root, out_dir)
    _render_final_gate(paper_root, out_dir)
    _render_manual_queue(paper_root, out_dir)
